controller_list:
  - name: fake_wam_arm_controller
    joints:
      - j1_joint
      - j2_joint
      - j3_joint
      - j4_joint
      - j5_joint
      - j6_joint
      - j7_joint
  - name: fake_x_wam_base_controller
    joints:
      - scissor_prismatic_joint
  - name: fake_x_wam_wheels_controller
    joints:
      - joint_back_left_steer
      - joint_back_left_wheel
      - joint_back_right_steer
      - joint_back_right_wheel
      - joint_front_left_steer
      - joint_front_left_wheel
      - joint_front_right_steer
      - joint_front_right_wheel